# -*- coding: utf-8 -*-
"""Exploratory Data Analysis - Retail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5CC4DAh3VRHYiQN8SCWvZtoIKpTYldy

<font color= "#660000" size='6'> <b>Author: Rutika Mehta </b> </font>

<B> <font size=**5**>Exploratory Data Analysis - Retail </font></b><br>
<br> <b>Problem Statement: </b> 
Perform ‘Exploratory Data Analysis’ on dataset ‘SampleSuperstore’ This task is about Exploratory Data Analysis - Retail where the task focuses on a business manager who will try to find out weak areas where he can work to make more profit.

- Importing Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive/MyDrive/GRIP\ 2021

df = pd.read_csv('SampleSuperstore.csv')  #loading dataset
df.head()    #display top 5 rows

df.tail()     #bottom 5 rows

df.shape

df.describe()       #display summary

df.isnull().sum()       #checking null values

df.info()           #information about dataset

df.columns

df.duplicated().sum()

df.nunique()

df['Postal Code'] = df['Postal Code'].astype('object')

df.drop_duplicates(subset=None,keep='first',inplace=True)
df.duplicated().sum()

corr = df.corr()
sns.heatmap(corr,annot=True,cmap='Reds')

df = df.drop(['Postal Code'],axis = 1)    #dropping postal code columns

sns.pairplot(df, hue = 'Ship Mode')

df['Ship Mode'].value_counts()

sns.countplot(x=df['Ship Mode'])

df['Segment'].value_counts()        #valuecounts for segment

sns.pairplot(df,hue = 'Segment')     #plotting pair plot

sns.countplot(x = 'Segment',data = df, palette = 'rainbow')

df['Category'].value_counts()

sns.countplot(x='Category',data=df,palette='tab10')

sns.pairplot(df,hue='Category')

df['Sub-Category'].value_counts()

plt.figure(figsize=(10,8))
df['Sub-Category'].value_counts().plot.pie(autopct='dark')
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 1: <br> </b> </font>
Maximum are from Binders, Paper, furnishings, Phones, storage, art, accessories and minimum from copiers, machines, suppliers
"""

df['State'].value_counts()

plt.figure(figsize=(10,6))
sns.countplot(x='State',data=df,palette='rocket_r',order=df['State'].value_counts().index)
plt.xticks(rotation=90)
plt.show()

"""<font color= "#660000" size='6'> <b>Observation 2: <br></b></font>

*   Highest number of buyers are from California and New York


"""

df.hist(figsize=(10,10),bins=50)
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 3 </b> </font> <br>
- Most customers tends to buy quantity of 2 and 3 <br>
- Discount give maximum is 0 to 20 percent<br>
"""

plt.figure(figsize=(10,8))
df['Region'].value_counts().plot.pie(autopct = '%1.1f%%')
plt.show()

"""<font color= "#660000" size='6'> <b> Profit vs Discount: """

fig,ax=plt.subplots(figsize=(10,6))
ax.scatter(df['Sales'],df['Profit'])
ax.set_xlabel('Sales')
ax.set_ylabel('Profit')
plt.show()

sns.lineplot(x='Discount',y='Profit',label='Profit',data=df)
plt.legend()
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 4 <br> </b> </font>
- No correlation between profit and discount<br><br>

<font color= "#660000" size='6'> <b> Profit vs Quantity
"""

sns.lineplot(x='Quantity',y='Profit',label='Profit',data=df)
plt.legend()
plt.show()

df.groupby('Segment')[['Profit','Sales']].sum().plot.bar(color=['orange','blue'],figsize=(8,5))
plt.ylabel('Profit/Loss and sales')
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 5 <br> </b> </font>
- Profit and sales are maximum in consumer segment and minimum in Home Office segment
"""

plt.figure(figsize=(12,8))
plt.title('Segment wise Sales in each Region')
sns.barplot(x='Region',y='Sales',data=df,hue='Segment',order=df['Region'].value_counts().index,palette='rocket')
plt.xlabel('Region',fontsize=15)
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 6 <br> </b> </font>
- Segment wise sales are almost same in every region
"""

df.groupby('Region')[['Profit','Sales']].sum().plot.bar(color=['blue','red'],figsize=(8,5))
plt.ylabel('Profit/Loss and sales')
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 7 <br> </b> </font>
- Profit and sales are maximum in west region and minimum in south region
"""

ps = df.groupby('State')[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)
ps[:].plot.bar(color=['blue','orange'],figsize=(10,6))
plt.title('Profit/loss & Sales across states')
plt.xlabel('States')
plt.ylabel('Profit/loss & Sales')
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 8 <br> </b></font>
- High profit is for California, New York<br>
- Loss is for Texas, Pennsylvania, Ohio
"""

t_states = df['State'].value_counts().nlargest(10)
t_states

df.groupby('Category')[['Profit','Sales']].sum().plot.bar(color=['yellow','purple'],alpha=0.9,figsize=(8,5))
plt.ylabel('Profit/Loss and sales')
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 9 <br> </b> </font>
#### As a business manager, try to find out the weak areas where you can work to make more profit?<br>

- Technology and Office Supplies have high profit.<br>
- Furniture have less profit<br>
"""

ps = df.groupby('Sub-Category')[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)
ps[:].plot.bar(color=['red','#330066'],figsize=(10,6))
plt.title('Profit/loss & Sales across states')
plt.xlabel('Sub-Category')
plt.ylabel('Profit/loss & Sales')
plt.show()

"""<font color= "#660000" size='6'> <b> Observation 10<br> </b> </font>

- Phones sub-category have high sales.<br>
- Chairs have high sales but less profit compared to phones<br>
- Tables and Bookmarks sub-categories facing huge loss<br>

<font color= "#003366" size='8'> <b> Thank You!
"""